import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'bn';

export interface TranslationDictionary {
  nav: {
    dashboard: string;
    complaints: string;
    responses: string;
    categories: string;
    map: string;
    locationActivity: string;
    roles: string;
    users: string;
  };
  header: {
    searchPlaceholder: string;
    notifications: string;
    themeToggle: string;
    profile: string;
    superadmin: string;
    operator: string;
    signOut: string;
    systemStatus: string;
    operational: string;
  };
  common: {
    back: string;
    refresh: string;
    filter: string;
    export: string;
    search: string;
    actions: string;
    status: string;
    viewDetails: string;
    close: string;
    save: string;
    cancel: string;
  };
  access: {
    restrictedTitle: string;
    restrictedDescription: string;
    requiredPermission: string;
    assignedRole: string;
    noRoleAssigned: string;
    backToDashboard: string;
    evidenceRestricted: string;
    evidenceRestrictedDesc: string;
    noActionsAllowed: string;
    exportRestricted: string;
  };
  roles: {
    title: string;
    description: string;
    refresh: string;
    createRole: string;
    createRoleNotAvailable: string;
    roleName: string;
    status: string;
    permissions: string;
    assignedUsers: string;
    created: string;
    active: string;
    inactive: string;
    system: string;
    emptyTitle: string;
    emptyDescription: string;
    showingTotalSingular: string;
    showingTotalPlural: string;
    permissionSingular: string;
    permissionPlural: string;
    userSingular: string;
    userPlural: string;
    createdLabel: string;
    permissionRequired: string;
    permissionDeniedMessage: string;
    failedToLoad: string;
    failedToLoadMessage: string;
    retry: string;
    createRoleTitle: string;
    createRoleSubtitle: string;
    step1Title: string;
    step1Description: string;
    step2Title: string;
    step2Description: string;
    step3Title: string;
    step3Description: string;
    enterRoleName: string;
    roleNamePlaceholder: string;
    roleNameRequired: string;
    roleNameHelper: string;
    roleNameEnglish: string;
    roleNameEnglishHelper: string;
    roleNameEnglishPlaceholder: string;
    roleNameEnglishRequired: string;
    roleNameEnglishInvalidSlug: string;
    roleNameBengali: string;
    roleNameBengaliOptional: string;
    roleNameBengaliPlaceholder: string;
    roleNameBengaliHelper: string;
    technicalRoleIdPreview: string;
    technicalRoleIdPreviewHelper: string;
    enterEnglishNameToPreviewId: string;
    technicalIdAutoGenerated: string;
    technicalIdPrefix: string;
    technicalIdExample: string;
    descriptionLabel: string;
    descriptionOptional: string;
    descriptionPlaceholder: string;
    statusActiveDesc: string;
    statusInactiveDesc: string;
    selectAll: string;
    clearAll: string;
    selectedCount: string;
    permissionsCount: string;
    noPermissionsWarning: string;
    rolesManageWarning: string;
    reviewRoleDetails: string;
    reviewPermissions: string;
    submitting: string;
    roleCreatedSuccess: string;
    duplicateNameError: string;
    permissionDeniedCreate: string;
    createCompatibilityError: string;
    generalCreateError: string;
    loadPermissionsError: string;
    cancelConfirmTitle: string;
    cancelConfirmMessage: string;
    keepEditing: string;
    discardAndLeave: string;
    edit: string;
    next: string;
    back: string;
    cancel: string;
    moduleDashboard: string;
    moduleComplaints: string;
    moduleCategories: string;
    moduleMap: string;
    moduleLocationActivity: string;
    moduleResponses: string;
    moduleAdminUsers: string;
    moduleRoles: string;
    moduleAudit: string;
    // Role Detail & Edit additions (Phase 2B)
    roleDetailTitle: string;
    roleDetailSubtitle: string;
    backToRoles: string;
    backToDetail: string;
    editRole: string;
    editRoleTitle: string;
    editRoleSubtitle: string;
    technicalRoleId: string;
    technicalRoleIdHelper: string;
    englishName: string;
    bengaliName: string;
    notSpecified: string;
    roleType: string;
    systemRole: string;
    customRole: string;
    lastUpdated: string;
    neverUpdated: string;
    assignedPermissions: string;
    noAssignedPermissions: string;
    noAssignedPermissionsDesc: string;
    assignedCountBadge: string;
    systemRoleProtectedNotice: string;
    systemRoleProtectedEditNotice: string;
    roleNotFoundTitle: string;
    roleNotFoundMessage: string;
    viewDetails: string;
    saveChanges: string;
    savingChanges: string;
    roleUpdatedSuccess: string;
    noChangesDetected: string;
    readOnlyField: string;
    bengaliNameNotice: string;
    lastManagerError: string;
    systemRoleError: string;
    compatibilityError: string;
    copyId: string;
    idCopied: string;
    activeStatusHelper: string;
    inactiveStatusHelper: string;
    viewRole: string;
    noDescriptionProvided: string;
    descriptionEditHelper: string;
    configurationError: string;
    dismissMessage: string;
  };
  users: {
    title: string;
    description: string;
    createUser: string;
    editUser: string;
    viewUser: string;
    searchPlaceholder: string;
    filterRole: string;
    filterStatus: string;
    allRoles: string;
    allStatuses: string;
    active: string;
    inactive: string;
    displayName: string;
    email: string;
    password: string;
    confirmPassword: string;
    role: string;
    selectRole: string;
    status: string;
    superAdmin: string;
    standardAdmin: string;
    accountType: string;
    created: string;
    lastUpdated: string;
    protectedAccount: string;
    protectedAccountNotice: string;
    protectedAccountDesc: string;
    noUsersFound: string;
    noUsersFoundDesc: string;
    createUserTitle: string;
    createUserDesc: string;
    editUserTitle: string;
    editUserDesc: string;
    passwordMismatch: string;
    passwordLengthError: string;
    emailRequired: string;
    roleRequired: string;
    userCreatedSuccess: string;
    userUpdatedSuccess: string;
    saveUser: string;
    savingUser: string;
    creatingUser: string;
    superAdminCannotBeEdited: string;
    superAdminCannotBeDeactivated: string;
    effectivePermissions: string;
    fullSystemAccess: string;
    roleBasedAccess: string;
    emailImmutableNotice: string;
    backToUsers: string;
    configurationError: string;
  };
}

export const translations: Record<Language, TranslationDictionary> = {
  en: {
    nav: {
      dashboard: 'Dashboard',
      complaints: 'Complaints',
      responses: 'Responses',
      categories: 'Categories',
      map: 'Map Monitoring',
      locationActivity: 'Location Activity',
      roles: 'Roles & Permissions',
      users: 'Admin Users',
    },
    header: {
      searchPlaceholder: 'Search complaints, IDs, wards...',
      notifications: 'Notifications',
      themeToggle: 'Toggle theme',
      profile: 'Admin Profile',
      superadmin: 'Superadmin',
      operator: 'Admin Operator',
      signOut: 'Sign Out',
      systemStatus: 'System Status',
      operational: 'Operational',
    },
    common: {
      back: 'Back',
      refresh: 'Refresh',
      filter: 'Filter',
      export: 'Export',
      search: 'Search',
      actions: 'Actions',
      status: 'Status',
      viewDetails: 'View Details',
      close: 'Close',
      save: 'Save',
      cancel: 'Cancel',
    },
    access: {
      restrictedTitle: 'Access Restricted',
      restrictedDescription: 'You do not have administrative permission to access this module.',
      requiredPermission: 'Required Permission:',
      assignedRole: 'Your Assigned Role:',
      noRoleAssigned: 'No Role Assigned (Zero Permissions)',
      backToDashboard: 'Back to Overview',
      evidenceRestricted: 'Evidence Inspection Restricted',
      evidenceRestrictedDesc: 'Your assigned role does not have the "complaints.evidence_view" permission to view citizen-submitted media.',
      noActionsAllowed: 'No triage actions permitted. (Read-only access)',
      exportRestricted: 'You do not have permission to export complaints.',
    },
    roles: {
      title: 'Roles & Permissions',
      description: 'Manage administrative roles and their system permissions.',
      refresh: 'Refresh',
      createRole: 'Create Role',
      createRoleNotAvailable: 'Create Role is not available yet.',
      roleName: 'Role Name',
      status: 'Status',
      permissions: 'Permissions',
      assignedUsers: 'Assigned Users',
      created: 'Created',
      active: 'Active',
      inactive: 'Inactive',
      system: 'System',
      emptyTitle: 'No roles created yet',
      emptyDescription: 'Create roles to define which areas and actions administrators can access.',
      showingTotalSingular: 'Showing 1 total role',
      showingTotalPlural: 'Showing {count} total roles',
      permissionSingular: 'permission',
      permissionPlural: 'permissions',
      userSingular: 'user',
      userPlural: 'users',
      createdLabel: 'Created:',
      permissionRequired: 'Permission Required',
      permissionDeniedMessage: 'You do not have permission to access Roles & Permissions.',
      failedToLoad: 'Failed to load roles',
      failedToLoadMessage: 'Could not load administrative roles. Please check your connection and retry.',
      retry: 'Retry',
      // Create Role Flow
      createRoleTitle: 'Create Role',
      createRoleSubtitle: 'Define a new administrative role and assign its system permissions.',
      step1Title: 'Role Details',
      step1Description: 'Define the role name and status.',
      step2Title: 'Permissions',
      step2Description: 'Assign system access permissions to this administrative role.',
      step3Title: 'Review',
      step3Description: 'Review role configuration and permissions before creating.',
      enterRoleName: 'Enter role name',
      roleNamePlaceholder: 'Enter role name',
      roleNameRequired: 'Role name is required and cannot be blank.',
      roleNameHelper: 'A clear, descriptive name for this administrative role.',
      roleNameEnglish: 'Role Name (English)',
      roleNameEnglishHelper: 'A clear English name used to derive the permanent technical Role ID.',
      roleNameEnglishPlaceholder: 'e.g. Content Moderator, Department Inspector',
      roleNameEnglishRequired: 'English role name is required and cannot be blank.',
      roleNameEnglishInvalidSlug: 'Role name must contain English letters or numbers to generate a technical ID.',
      roleNameBengali: 'Role Name (Bengali)',
      roleNameBengaliOptional: 'Role Name (Bengali) (Optional)',
      roleNameBengaliPlaceholder: 'e.g. কন্টেন্ট মডারেটর',
      roleNameBengaliHelper: 'Displayed to administrators using the Bengali interface. Does not affect the technical ID.',
      technicalRoleIdPreview: 'Technical Role ID',
      technicalRoleIdPreviewHelper: 'Permanent system identifier used for authorization checks. Automatically derived from English name.',
      enterEnglishNameToPreviewId: 'Enter an English role name above to preview generated technical ID.',
      technicalIdAutoGenerated: 'Auto-generated',
      technicalIdPrefix: 'ID:',
      technicalIdExample: 'e.g. content-moderator',
      descriptionLabel: 'Description',
      descriptionOptional: 'Description (Optional)',
      descriptionPlaceholder: 'Add an optional description',
      statusActiveDesc: 'Users assigned to this role can immediately exercise its permissions.',
      statusInactiveDesc: 'Role is disabled. Users assigned will not inherit its permissions until activated.',
      selectAll: 'Select All',
      clearAll: 'Clear All',
      selectedCount: '{count} selected',
      permissionsCount: '{count} of {total} permissions selected',
      noPermissionsWarning: 'No permissions selected. This role will not be able to access permission-controlled features.',
      rolesManageWarning: 'This role will not be able to manage Roles & Permissions.',
      reviewRoleDetails: 'Role Details',
      reviewPermissions: 'Permissions',
      submitting: 'Creating Role...',
      roleCreatedSuccess: 'Role created successfully.',
      duplicateNameError: 'A role with this name already exists.',
      permissionDeniedCreate: 'You do not have permission to manage Roles & Permissions.',
      createCompatibilityError: 'Role creation is temporarily unavailable because the required bilingual role update has not been applied. Please contact your system administrator.',
      generalCreateError: 'Failed to create role. Please check your connection and retry.',
      loadPermissionsError: 'Could not load permissions catalogue. Please check your connection and retry.',
      cancelConfirmTitle: 'Discard changes?',
      cancelConfirmMessage: 'You have unsaved changes in this role. Leaving will discard all entered details.',
      keepEditing: 'Keep Editing',
      discardAndLeave: 'Discard and Leave',
      edit: 'Edit',
      next: 'Next',
      back: 'Back',
      cancel: 'Cancel',
      moduleDashboard: 'Dashboard',
      moduleComplaints: 'Complaints',
      moduleCategories: 'Categories',
      moduleMap: 'Map Monitoring',
      moduleLocationActivity: 'Location Activity',
      moduleResponses: 'Responses',
      moduleAdminUsers: 'User Management',
      moduleRoles: 'Roles & Permissions',
      moduleAudit: 'Audit',
      // Role Detail & Edit additions (Phase 2B)
      roleDetailTitle: 'Role Details',
      roleDetailSubtitle: 'Inspect role metadata, status, and assigned permissions.',
      backToRoles: 'Back to Roles',
      backToDetail: 'Back to Role Details',
      editRole: 'Edit Role',
      editRoleTitle: 'Edit Role',
      editRoleSubtitle: 'Update role settings, description, and assigned permissions.',
      technicalRoleId: 'Technical Role ID',
      technicalRoleIdHelper: 'Permanent system identifier used for authorization checks.',
      englishName: 'Role Name (English)',
      bengaliName: 'Role Name (Bengali)',
      notSpecified: 'Not specified',
      roleType: 'Role Type',
      systemRole: 'System Role',
      customRole: 'Custom Role',
      lastUpdated: 'Last Updated',
      neverUpdated: 'Never updated',
      assignedPermissions: 'Assigned Permissions',
      noAssignedPermissions: 'No permissions assigned to this role',
      noAssignedPermissionsDesc: 'Users with this role will not have access to permission-controlled administrative features.',
      assignedCountBadge: '{count} assigned',
      systemRoleProtectedNotice: 'This is a protected system role. Core settings and permissions cannot be changed.',
      systemRoleProtectedEditNotice: 'Core configuration (name, status, and permissions) for system roles is permanently locked. Only the description can be modified.',
      roleNotFoundTitle: 'Role Not Found',
      roleNotFoundMessage: 'The requested administrative role does not exist or may have been removed.',
      viewDetails: 'View Details',
      saveChanges: 'Save Changes',
      savingChanges: 'Saving Changes...',
      roleUpdatedSuccess: 'Role updated successfully.',
      noChangesDetected: 'No changes detected',
      readOnlyField: 'Read-only',
      bengaliNameNotice: 'Bengali role name is preserved and managed separately.',
      lastManagerError: 'Operation rejected: Cannot modify or deactivate this role because it would leave no active administrators with role management permissions.',
      systemRoleError: 'System roles are protected by security policies. Core settings and permissions cannot be changed.',
      compatibilityError: 'Role updates are temporarily unavailable because the required backend update has not been applied. Please contact your system administrator.',
      copyId: 'Copy ID',
      idCopied: 'ID Copied',
      activeStatusHelper: 'Active roles grant their permissions to assigned users.',
      inactiveStatusHelper: 'Inactive roles do not grant permissions to assigned users.',
      viewRole: 'View',
      noDescriptionProvided: 'No description provided for this role.',
      descriptionEditHelper: 'Brief summary of the role responsibilities.',
      configurationError: 'Role management is not configured in this environment.',
      dismissMessage: 'Dismiss message',
    },
    users: {
      title: 'Administrator Accounts',
      description: 'Manage administrative users, credentials, assigned roles, and operational access.',
      createUser: 'Create Administrator',
      editUser: 'Edit Administrator',
      viewUser: 'View Details',
      searchPlaceholder: 'Search administrators by name or email...',
      filterRole: 'Filter by Role',
      filterStatus: 'Filter by Status',
      allRoles: 'All Roles',
      allStatuses: 'All Statuses',
      active: 'Active',
      inactive: 'Inactive',
      displayName: 'Display Name',
      email: 'Email Address',
      password: 'Initial Password',
      confirmPassword: 'Confirm Password',
      role: 'Assigned Role',
      selectRole: 'Select a role...',
      status: 'Account Status',
      superAdmin: 'Super Administrator',
      standardAdmin: 'Administrator',
      accountType: 'Account Type',
      created: 'Created',
      lastUpdated: 'Last Updated',
      protectedAccount: 'Protected System Account',
      protectedAccountNotice: 'Protected System Account',
      protectedAccountDesc: 'This account is designated as the primary Super Administrator with irrevocable full access. It cannot be edited, reassigned, deactivated, or deleted.',
      noUsersFound: 'No administrators found',
      noUsersFoundDesc: 'No administrator accounts match your active search or filter criteria.',
      createUserTitle: 'Create Administrator',
      createUserDesc: 'Provision a new administrative user with Supabase credentials and an assigned role.',
      editUserTitle: 'Edit Administrator',
      editUserDesc: 'Modify display name, assigned role, or active status for this administrator.',
      passwordMismatch: 'Passwords do not match.',
      passwordLengthError: 'Password must be at least 6 characters.',
      emailRequired: 'A valid email address is required.',
      roleRequired: 'A role assignment is required.',
      userCreatedSuccess: 'Administrator created successfully.',
      userUpdatedSuccess: 'Administrator updated successfully.',
      saveUser: 'Save Changes',
      savingUser: 'Saving Changes...',
      creatingUser: 'Creating Administrator...',
      superAdminCannotBeEdited: 'Super Administrator accounts are protected and cannot be edited.',
      superAdminCannotBeDeactivated: 'Super Administrator accounts cannot be deactivated.',
      effectivePermissions: 'Effective System Permissions',
      fullSystemAccess: 'Full System Access (Irrevocable)',
      roleBasedAccess: 'Permissions derived from assigned role:',
      emailImmutableNotice: 'Login email address is immutable and cannot be modified.',
      backToUsers: 'Back to Administrators',
      configurationError: 'User management is not configured in this environment.',
    },
  },
  bn: {
    nav: {
      dashboard: 'ড্যাশবোর্ড',
      complaints: 'অভিযোগসমূহ',
      responses: 'প্রতিক্রিয়া',
      categories: 'বিভাগসমূহ',
      map: 'ম্যাপ মনিটরিং',
      locationActivity: 'লোকেশন অ্যাক্টিভিটি',
      roles: 'ভূমিকা ও অনুমতি',
      users: 'অ্যাডমিন ইউজার',
    },
    header: {
      searchPlaceholder: 'অভিযোগ, আইডি, ওয়ার্ড অনুসন্ধান করুন...',
      notifications: 'বিজ্ঞপ্তি',
      themeToggle: 'থিম পরিবর্তন',
      profile: 'অ্যাডমিন প্রোফাইল',
      superadmin: 'সুপার অ্যাডমিন',
      operator: 'অ্যাডমিন অপারেটর',
      signOut: 'লগ আউট',
      systemStatus: 'সিস্টেম স্ট্যাটাস',
      operational: 'সক্রিয়',
    },
    common: {
      back: 'পিছনে যান',
      refresh: 'রিফ্রেশ',
      filter: 'ফিল্টার',
      export: 'এক্সপোর্ট',
      search: 'অনুসন্ধান',
      actions: 'পদক্ষেপ',
      status: 'অবস্থা',
      viewDetails: 'বিস্তারিত দেখুন',
      close: 'বন্ধ করুন',
      save: 'সংরক্ষণ',
      cancel: 'বাতিল',
    },
    access: {
      restrictedTitle: 'অ্যাক্সেস সীমাবদ্ধ',
      restrictedDescription: 'এই মডিউলে প্রবেশ করার জন্য আপনার প্রশাসনিক অনুমতি নেই।',
      requiredPermission: 'প্রয়োজনীয় অনুমতি:',
      assignedRole: 'আপনার বর্তমান ভূমিকা:',
      noRoleAssigned: 'কোনো ভূমিকা বরাদ্দ নেই (অনুমতি শূন্য)',
      backToDashboard: 'ওভারভিউতে ফিরে যান',
      evidenceRestricted: 'সংবেদনশীল প্রমাণাদি দেখার অনুমতি নেই',
      evidenceRestrictedDesc: 'নাগরিকদের জমা দেওয়া প্রমাণ বা ছবি দেখতে আপনার অ্যাকাউন্টে "complaints.evidence_view" অনুমতি প্রয়োজন।',
      noActionsAllowed: 'পদক্ষেপ গ্রহণের অনুমতি নেই (শুধুমাত্র দর্শনযোগ্য)',
      exportRestricted: 'অভিযোগ এক্সপোর্ট করার অনুমতি নেই।',
    },
    roles: {
      title: 'ভূমিকা ও অনুমতি',
      description: 'প্রশাসনিক ভূমিকা এবং তাদের সিস্টেমের অনুমতি পরিচালনা করুন।',
      refresh: 'রিফ্রেশ',
      createRole: 'ভূমিকা তৈরি করুন',
      createRoleNotAvailable: 'ভূমিকা তৈরি এখনো উপলভ্য নয়।',
      roleName: 'ভূমিকার নাম',
      status: 'স্ট্যাটাস',
      permissions: 'অনুমতি',
      assignedUsers: 'বরাদ্দকৃত ব্যবহারকারী',
      created: 'তৈরির তারিখ',
      active: 'সক্রিয়',
      inactive: 'নিষ্ক্রিয়',
      system: 'সিস্টেম',
      emptyTitle: 'এখনো কোনো ভূমিকা তৈরি করা হয়নি',
      emptyDescription: 'অ্যাডমিনিস্ট্রেটররা কোন ক্ষেত্র এবং কার্যকলাপে প্রবেশ করতে পারবেন তা নির্ধারণ করতে ভূমিকা তৈরি করুন।',
      showingTotalSingular: 'মোট ১ টি ভূমিকা তৈরি আছে',
      showingTotalPlural: 'মোট {count} টি ভূমিকা তৈরি আছে',
      permissionSingular: 'টি অনুমতি',
      permissionPlural: 'টি অনুমতি',
      userSingular: 'জন ব্যবহারকারী',
      userPlural: 'জন ব্যবহারকারী',
      createdLabel: 'তৈরির তারিখ:',
      permissionRequired: 'অনুমতি প্রয়োজন',
      permissionDeniedMessage: 'আপনার ভূমিকা ও অনুমতি এক্সেস করার অনুমতি নেই।',
      failedToLoad: 'ভূমিকা লোড করা যায়নি',
      failedToLoadMessage: 'প্রশাসনিক ভূমিকা লোড করা যায়নি। অনুগ্রহ করে আপনার সংযোগ পরীক্ষা করুন এবং আবার চেষ্টা করুন।',
      retry: 'আবার চেষ্টা করুন',
      // Create Role Flow
      createRoleTitle: 'ভূমিকা তৈরি করুন',
      createRoleSubtitle: 'একটি নতুন প্রশাসনিক ভূমিকা সংজ্ঞায়িত করুন এবং এর সিস্টেমের অনুমতি নির্ধারণ করুন।',
      step1Title: 'ভূমিকার বিবরণ',
      step1Description: 'ভূমিকার নাম এবং স্ট্যাটাস নির্ধারণ করুন।',
      step2Title: 'অনুমতিসমূহ',
      step2Description: 'এই প্রশাসনিক ভূমিকায় সিস্টেমের প্রবেশাধিকার অনুমতি বরাদ্দ করুন।',
      step3Title: 'পর্যালোচনা',
      step3Description: 'তৈরি করার আগে ভূমিকার কনফিগারেশন এবং অনুমতি পর্যালোচনা করুন।',
      enterRoleName: 'ভূমিকার নাম লিখুন',
      roleNamePlaceholder: 'ভূমিকার নাম লিখুন',
      roleNameRequired: 'ভূমিকার নাম আবশ্যক এবং ফাঁকা রাখা যাবে না।',
      roleNameHelper: 'এই প্রশাসনিক ভূমিকার জন্য একটি স্পষ্ট ও বর্ণনামূলক নাম।',
      roleNameEnglish: 'ভূমিকার নাম (ইংরেজি)',
      roleNameEnglishHelper: 'স্থায়ী টেকনিক্যাল ভূমিকা আইডি তৈরির জন্য একটি সুস্পষ্ট ইংরেজি নাম।',
      roleNameEnglishPlaceholder: 'যেমন: Content Moderator, Department Inspector',
      roleNameEnglishRequired: 'ইংরেজি ভূমিকার নাম আবশ্যক এবং ফাঁকা রাখা যাবে না।',
      roleNameEnglishInvalidSlug: 'টেকনিক্যাল আইডি তৈরির জন্য ভূমিকার নামে ইংরেজি অক্ষর বা সংখ্যা থাকতে হবে।',
      roleNameBengali: 'ভূমিকার নাম (বাংলা)',
      roleNameBengaliOptional: 'ভূমিকার নাম (বাংলা) (ঐচ্ছিক)',
      roleNameBengaliPlaceholder: 'যেমন: কন্টেন্ট মডারেটর',
      roleNameBengaliHelper: 'বাংলা ইন্টারফেস ব্যবহারকারী প্রশাসকদের জন্য প্রদর্শিত হবে। এটি টেকনিক্যাল আইডিতে প্রভাব ফেলে না।',
      technicalRoleIdPreview: 'টেকনিক্যাল ভূমিকা আইডি',
      technicalRoleIdPreviewHelper: 'অনুমতি যাচাইয়ের জন্য স্থায়ী সিস্টেম শনাক্তকারী। ইংরেজি নাম থেকে স্বয়ংক্রিয়ভাবে তৈরি হয়।',
      enterEnglishNameToPreviewId: 'টেকনিক্যাল ভূমিকা আইডি তৈরি দেখতে উপরে একটি ইংরেজি ভূমিকার নাম লিখুন।',
      technicalIdAutoGenerated: 'স্বয়ংক্রিয়ভাবে তৈরি',
      technicalIdPrefix: 'আইডি:',
      technicalIdExample: 'যেমন: content-moderator',
      descriptionLabel: 'বিবরণ',
      descriptionOptional: 'বিবরণ (ঐচ্ছিক)',
      descriptionPlaceholder: 'একটি ঐচ্ছিক বিবরণ যুক্ত করুন',
      statusActiveDesc: 'এই ভূমিকায় বরাদ্দকৃত ব্যবহারকারীরা অবিলম্বে এর অনুমতি ব্যবহার করতে পারবেন।',
      statusInactiveDesc: 'ভূমিকাটি নিষ্ক্রিয়। সক্রিয় না করা পর্যন্ত বরাদ্দকৃত ব্যবহারকারীরা এর অনুমতি পাবেন না।',
      selectAll: 'সব নির্বাচন করুন',
      clearAll: 'সব মুছুন',
      selectedCount: '{count} টি নির্বাচিত',
      permissionsCount: '{total} টির মধ্যে {count} টি অনুমতি নির্বাচিত',
      noPermissionsWarning: 'কোনো অনুমতি নির্বাচন করা হয়নি। এই ভূমিকাটি কোনো সুরক্ষিত বৈশিষ্ট্যে প্রবেশ করতে পারবে না।',
      rolesManageWarning: 'এই ভূমিকাটি ভূমিকা ও অনুমতি পরিচালনা করতে পারবে না।',
      reviewRoleDetails: 'ভূমিকার বিবরণ',
      reviewPermissions: 'অনুমতিসমূহ',
      submitting: 'ভূমিকা তৈরি করা হচ্ছে...',
      roleCreatedSuccess: 'ভূমিকা সফলভাবে তৈরি হয়েছে।',
      duplicateNameError: 'এই নামের একটি ভূমিকা ইতিমধ্যে বিদ্যমান।',
      permissionDeniedCreate: 'ভূমিকা ও অনুমতি পরিচালনা করার অনুমতি আপনার নেই।',
      createCompatibilityError: 'প্রয়োজনীয় দ্বিভাষিক ব্যাকএন্ড আপডেট প্রয়োগ না করায় ভূমিকা তৈরি সাময়িকভাবে অনুপলব্ধ। অনুগ্রহ করে সিস্টেম অ্যাডমিনিস্ট্রেটরের সাথে যোগাযোগ করুন।',
      generalCreateError: 'ভূমিকা তৈরি করতে ব্যর্থ হয়েছে। আপনার সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
      loadPermissionsError: 'অনুমতি তালিকা লোড করা যায়নি। অনুগ্রহ করে আপনার সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
      cancelConfirmTitle: 'পরিবর্তন বাতিল করবেন?',
      cancelConfirmMessage: 'আপনার ভূমিকায় অসংরক্ষিত পরিবর্তন রয়েছে। ফিরে গেলে সমস্ত তথ্য মুছে যাবে।',
      keepEditing: 'সম্পাদনা চালিয়ে যান',
      discardAndLeave: 'বাতিল করে ফিরে যান',
      edit: 'সম্পাদনা',
      next: 'পরবর্তী',
      back: 'পূর্ববর্তী',
      cancel: 'বাতিল',
      moduleDashboard: 'ড্যাশবোর্ড',
      moduleComplaints: 'অভিযোগসমূহ',
      moduleCategories: 'বিভাগসমূহ',
      moduleMap: 'ম্যাপ মনিটরিং',
      moduleLocationActivity: 'লোকেশন অ্যাক্টিভিটি',
      moduleResponses: 'প্রতিক্রিয়া',
      moduleAdminUsers: 'ব্যবহারকারী পরিচালনা',
      moduleRoles: 'ভূমিকা ও অনুমতি',
      moduleAudit: 'অডিট',
      // Role Detail & Edit additions (Phase 2B)
      roleDetailTitle: 'ভূমিকার বিবরণ',
      roleDetailSubtitle: 'ভূমিকার মেটাডাটা, স্ট্যাটাস এবং বরাদ্দকৃত অনুমতি পর্যালোচনা করুন।',
      backToRoles: 'ভূমিকা তালিকায় ফিরুন',
      backToDetail: 'ভূমিকার বিবরণে ফিরুন',
      editRole: 'ভূমিকা সম্পাদনা',
      editRoleTitle: 'ভূমিকা সম্পাদনা',
      editRoleSubtitle: 'ভূমিকার সেটিংস, বিবরণ এবং বরাদ্দকৃত অনুমতি হালনাগাদ করুন।',
      technicalRoleId: 'টেকনিক্যাল ভূমিকা আইডি',
      technicalRoleIdHelper: 'অনুমতি যাচাইয়ের জন্য স্থায়ী সিস্টেম শনাক্তকারী।',
      englishName: 'ভূমিকার নাম (ইংরেজি)',
      bengaliName: 'ভূমিকার নাম (বাংলা)',
      notSpecified: 'নির্দিষ্ট করা নেই',
      roleType: 'ভূমিকার ধরন',
      systemRole: 'সিস্টেম ভূমিকা',
      customRole: 'কাস্টম ভূমিকা',
      lastUpdated: 'সর্বশেষ হালনাগাদ',
      neverUpdated: 'কখনো পরিবর্তন হয়নি',
      assignedPermissions: 'বরাদ্দকৃত অনুমতিসমূহ',
      noAssignedPermissions: 'এই ভূমিকায় কোনো অনুমতি বরাদ্দ নেই',
      noAssignedPermissionsDesc: 'এই ভূমিকার ব্যবহারকারীরা কোনো অনুমতি-নিয়ন্ত্রিত প্রশাসনিক ফিচারে প্রবেশাধিকার পাবেন না।',
      assignedCountBadge: '{count} টি বরাদ্দকৃত',
      systemRoleProtectedNotice: 'এটি একটি সুরক্ষিত সিস্টেম ভূমিকা। মূল সেটিংস ও অনুমতি পরিবর্তন করা যাবে না।',
      systemRoleProtectedEditNotice: 'সিস্টেম ভূমিকার মূল সেটিংস (নাম, স্ট্যাটাস এবং অনুমতি) স্থায়ীভাবে লক করা। শুধুমাত্র বিবরণ সম্পাদনা করা যাবে।',
      roleNotFoundTitle: 'ভূমিকা পাওয়া যায়নি',
      roleNotFoundMessage: 'অনুরোধকৃত প্রশাসনিক ভূমিকাটি বিদ্যমান নেই বা সরানো হয়ে থাকতে পারে।',
      viewDetails: 'বিস্তারিত দেখুন',
      saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
      savingChanges: 'সংরক্ষণ করা হচ্ছে...',
      roleUpdatedSuccess: 'ভূমিকা সফলভাবে হালনাগাদ হয়েছে।',
      noChangesDetected: 'কোনো পরিবর্তন করা হয়নি',
      readOnlyField: 'শুধুমাত্র পাঠযোগ্য',
      bengaliNameNotice: 'বাংলা ভূমিকার নাম সংরক্ষিত থাকে এবং আলাদাভাবে পরিচালিত হয়।',
      lastManagerError: 'কার্যক্রম বাতিল: এই ভূমিকাটি পরিবর্তন বা নিষ্ক্রিয় করা যাবে না কারণ এর ফলে সিস্টেমে ভূমিকা পরিচালনা করার মতো কোনো সক্রিয় প্রশাসক থাকবে না।',
      systemRoleError: 'সিস্টেম ভূমিকাগুলো নিরাপত্তা নীতি দ্বারা সুরক্ষিত। মূল সেটিংস ও অনুমতি পরিবর্তন করা যাবে না।',
      compatibilityError: 'প্রয়োজনীয় ব্যাকএন্ড আপডেট প্রয়োগ না করায় ভূমিকা আপডেট সাময়িকভাবে অনুপলব্ধ। অনুগ্রহ করে সিস্টেম অ্যাডমিনিস্ট্রেটরের সাথে যোগাযোগ করুন।',
      copyId: 'আইডি কপি করুন',
      idCopied: 'আইডি কপি করা হয়েছে',
      activeStatusHelper: 'সক্রিয় ভূমিকার অনুমতিগুলো বরাদ্দকৃত ব্যবহারকারীরা ব্যবহার করতে পারেন।',
      inactiveStatusHelper: 'নিষ্ক্রিয় ভূমিকার অনুমতিগুলো বরাদ্দকৃত ব্যবহারকারীরা ব্যবহার করতে পারেন না।',
      viewRole: 'দেখুন',
      noDescriptionProvided: 'কোনো বিবরণ প্রদান করা হয়নি।',
      descriptionEditHelper: 'ভূমিকার উদ্দেশ্য বা দায়িত্বের সংক্ষিপ্ত বিবরণ।',
      configurationError: 'এই পরিবেশে ভূমিকা ব্যবস্থাপনা কনফিগার করা নেই।',
      dismissMessage: 'বার্তাটি বন্ধ করুন',
    },
    users: {
      title: 'প্রশাসক অ্যাকাউন্টসমূহ',
      description: 'প্রশাসনিক ব্যবহারকারী, পরিচয়পত্র, বরাদ্দকৃত ভূমিকা এবং কার্যক্রমের অনুমতি পরিচালনা করুন।',
      createUser: 'প্রশাসক তৈরি করুন',
      editUser: 'প্রশাসক সম্পাদনা করুন',
      viewUser: 'বিস্তারিত দেখুন',
      searchPlaceholder: 'নাম বা ইমেইল দিয়ে প্রশাসক অনুসন্ধান করুন...',
      filterRole: 'ভূমিকা অনুযায়ী ফিল্টার',
      filterStatus: 'স্ট্যাটাস অনুযায়ী ফিল্টার',
      allRoles: 'সকল ভূমিকা',
      allStatuses: 'সকল স্ট্যাটাস',
      active: 'সক্রিয়',
      inactive: 'নিষ্ক্রিয়',
      displayName: 'প্রদর্শিত নাম',
      email: 'ইমেইল ঠিকানা',
      password: 'প্রাথমিক পাসওয়ার্ড',
      confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
      role: 'বরাদ্দকৃত ভূমিকা',
      selectRole: 'একটি ভূমিকা নির্বাচন করুন...',
      status: 'অ্যাকাউন্টের স্ট্যাটাস',
      superAdmin: 'সুপার অ্যাডমিনিস্ট্রেটর',
      standardAdmin: 'অ্যাডমিনিস্ট্রেটর',
      accountType: 'অ্যাকাউন্টের ধরন',
      created: 'তৈরি হয়েছে',
      lastUpdated: 'সর্বশেষ পরিবর্তন',
      protectedAccount: 'সুরক্ষিত সিস্টেম অ্যাকাউন্ট',
      protectedAccountNotice: 'সুরক্ষিত সিস্টেম অ্যাকাউন্ট',
      protectedAccountDesc: 'এই অ্যাকাউন্টটি প্রাথমিক সুপার অ্যাডমিনিস্ট্রেটর হিসেবে নির্ধারিত এবং এর সম্পূর্ণ অপরিবর্তনীয় অ্যাক্সেস রয়েছে। এটি সম্পাদনা, পুনর্বরাদ্দ, নিষ্ক্রিয় বা মুছে ফেলা যাবে না।',
      noUsersFound: 'কোনো প্রশাসক পাওয়া যায়নি',
      noUsersFoundDesc: 'আপনার অনুসন্ধান বা ফিল্টারের সাথে কোনো প্রশাসক অ্যাকাউন্ট মেলেনি।',
      createUserTitle: 'প্রশাসক তৈরি করুন',
      createUserDesc: 'সুপাবেস লগইন শংসাপত্র এবং বরাদ্দকৃত ভূমিকাসহ একজন নতুন প্রশাসক যুক্ত করুন।',
      editUserTitle: 'প্রশাসক সম্পাদনা করুন',
      editUserDesc: 'এই প্রশাসকের প্রদর্শিত নাম, বরাদ্দকৃত ভূমিকা বা সক্রিয় অবস্থা পরিবর্তন করুন।',
      passwordMismatch: 'পাসওয়ার্ড দুটি মেলেনি।',
      passwordLengthError: 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
      emailRequired: 'একটি বৈধ ইমেইল ঠিকানা প্রয়োজন।',
      roleRequired: 'একটি ভূমিকা বরাদ্দ করা আবশ্যক।',
      userCreatedSuccess: 'প্রশাসক সফলভাবে তৈরি করা হয়েছে।',
      userUpdatedSuccess: 'প্রশাসক তথ্য সফলভাবে হালনাগাদ হয়েছে।',
      saveUser: 'সংরক্ষণ করুন',
      savingUser: 'সংরক্ষণ করা হচ্ছে...',
      creatingUser: 'তৈরি করা হচ্ছে...',
      superAdminCannotBeEdited: 'সুপার অ্যাডমিনিস্ট্রেটর অ্যাকাউন্ট সুরক্ষিত এবং এটি সম্পাদনা করা যাবে না।',
      superAdminCannotBeDeactivated: 'সুপার অ্যাডমিনিস্ট্রেটর অ্যাকাউন্ট নিষ্ক্রিয় করা যাবে না।',
      effectivePermissions: 'কার্যকর সিস্টেম অনুমতিসমূহ',
      fullSystemAccess: 'সম্পূর্ণ সিস্টেম অ্যাক্সেস (স্থায়ী)',
      roleBasedAccess: 'বরাদ্দকৃত ভূমিকা থেকে প্রাপ্ত অনুমতি:',
      emailImmutableNotice: 'লগইন ইমেইল ঠিকানা অপরিবর্তনীয় এবং এটি পরিবর্তন করা যাবে না।',
      backToUsers: 'প্রশাসক তালিকায় ফিরুন',
      configurationError: 'এই পরিবেশে ব্যবহারকারী ব্যবস্থাপনা কনফিগার করা নেই।',
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: TranslationDictionary;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'sobaike_admin_lang';

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (saved === 'en' || saved === 'bn') return saved;
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    document.documentElement.lang = lang;
  };

  const toggleLanguage = () => {
    setLanguage(language === 'en' ? 'bn' : 'en');
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        toggleLanguage,
        t: translations[language],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
